# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - main

pool:
  vmImage: ubuntu-latest

#variables:
  #startsWith(variables['Build.SourceBranch'], 'refs/tags/')

steps:
- powershell: [string]$version = (git describe --tags) -replace "[^0-9, .]", ''
 $dotCount = $version.Length - ($version -replace "[^0-9]", '').Length
for($i = 1; $i -le 5; $i++){
if ($dotCount -lt 2 ) {
"$version" + ".0." + "$i" }
else { "$version" + "." + "$i" } }