# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - main
 tags:
    include:
      - all

pool:
  vmImage: ubuntu-latest

#variables:
  #startsWith(variables['Build.SourceBranch'], 'refs/tags/')

steps:
- script: echo $(last_tag)!
  displayName: 'Run a one-line script' 

- script: echo $tags
  displayName: 'Run a multi-line script'
