# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - '*'

pool:
  vmImage: 'windows-2022'

variables:
- name: vers
  value: string

steps:
- script: echo '$(Build.BuildNumber)'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [string]$version = ((git describe --tags) -replace "(?<=-).*", '') -replace "[^0-9, .]", ''
      $dotCount = $version.Length - ($version -replace "[^0-9]", '').Length
      if ($dotCount -lt 2 ) {
      $version = "$version" + ".0"}
- bash: echo "##vso[task.setvariable variable=vers]$version"

name: $tags$(Rev:.r)