# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
  
pool:
  vmImage: 'windows-2022'

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

steps:

- script: echo '$(Build.BuildNumber)'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [string]$version = ((git describe --tags) -replace "(?<=-).*", '') -replace "[^0-9, .]", ''
      $dotCount = $version.Length - ($version -replace "[^0-9]", '').Length
      if ($dotCount -lt 2 ) {
      "$version" + ".0." + "$(Build.BuildNumber)" }
      else { "$version" + "." + "$(Build.BuildNumber)" }